/*
 * This file is generated by jOOQ.
 */
package com.chelchowskidawidjan.tables.records;


import com.chelchowskidawidjan.tables.Filecomments;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FilecommentsRecord extends UpdatableRecordImpl<FilecommentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.filecomments.uuid</code>.
     */
    public void setUuid(String[] value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.filecomments.uuid</code>.
     */
    public String[] getUuid() {
        return (String[]) get(0);
    }

    /**
     * Setter for <code>public.filecomments.author</code>.
     */
    public void setAuthor(String[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.filecomments.author</code>.
     */
    public String[] getAuthor() {
        return (String[]) get(1);
    }

    /**
     * Setter for <code>public.filecomments.file</code>.
     */
    public void setFile(String[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.filecomments.file</code>.
     */
    public String[] getFile() {
        return (String[]) get(2);
    }

    /**
     * Setter for <code>public.filecomments.content</code>.
     */
    public void setContent(String[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.filecomments.content</code>.
     */
    public String[] getContent() {
        return (String[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String[]> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilecommentsRecord
     */
    public FilecommentsRecord() {
        super(Filecomments.FILECOMMENTS);
    }

    /**
     * Create a detached, initialised FilecommentsRecord
     */
    public FilecommentsRecord(String[] uuid, String[] author, String[] file, String[] content) {
        super(Filecomments.FILECOMMENTS);

        setUuid(uuid);
        setAuthor(author);
        setFile(file);
        setContent(content);
        resetTouchedOnNotNull();
    }
}
