/*
 * This file is generated by jOOQ.
 */
package com.chelchowskidawidjan;


import com.chelchowskidawidjan.tables.Filecomments;
import com.chelchowskidawidjan.tables.Filepermissions;
import com.chelchowskidawidjan.tables.Files;
import com.chelchowskidawidjan.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.filecomments</code>.
     */
    public static final Filecomments FILECOMMENTS = Filecomments.FILECOMMENTS;

    /**
     * The table <code>public.filepermissions</code>.
     */
    public static final Filepermissions FILEPERMISSIONS = Filepermissions.FILEPERMISSIONS;

    /**
     * The table <code>public.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
